Added deps to hopefully work with Maven 3.1.0
Trying to build the project with Maven 3.1.0 results in a:
java.lang.NoClassDefFoundError: Lorg/sonatype/aether/RepositorySystem;
Others experienced the same issue, because it appears that the aether project got moved or something. Based on changes to the AppEngine Maven Plugin, I've added dependencies to hopefully clear this up.